title: LaboMath
description: Ressources mathématiques — Lycée de Baudre
url: "https://labomath-baudre.github.io"
baseurl: ""

lang: fr
date_format: "%-d %B %Y"

markdown: kramdown

exclude:
  - README.md
  - .gitignore
