title: LaboMath
description: Ressources mathématiques — Lycée de Baudre
url: "https://labomath-baudre.github.io"
baseurl: ""

lang: fr
date_format: "%-d %B %Y"

markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  parse_span_html: true

exclude:
  - README.md
  - .gitignore
